name: Update DNS

on: [push, workflow_dispatch]

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up the update script
      run: |
        mkdir -p scripts
        echo '#!/bin/bash
        USERNAME="jtsv3rd"
        PASSWORD="Sjh846v5Ztyj"
        HOSTNAME="rdpghost.freedynamicdns.org"
        IP=$(curl -s http://api.ipify.org/)
        curl -u "$USERNAME:$PASSWORD" "https://freedynamicdns.org/api/update?hostname=$HOSTNAME&myip=$IP"' > scripts/update_dns.sh
        chmod +x scripts/update_dns.sh

    - name: Run DNS update script
      run: scripts/update_dns.sh
